# Example pyproject.toml for Python projects using uv
# Rename to pyproject.toml to use

[project]
name = "your-app-name"
version = "0.1.0"
description = "Your app description"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    # Web Frameworks - Choose one:
    # "fastapi>=0.109.0",
    # "flask>=3.0.0",
    # "django>=5.0.0",

    # ASGI Server (for FastAPI/async frameworks)
    # "uvicorn[standard]>=0.27.0",

    # Database
    # "sqlalchemy>=2.0.25",
    # "psycopg2-binary>=2.9.9",  # PostgreSQL
    # "pymongo>=4.6.1",  # MongoDB

    # Utilities
    # "requests>=2.31.0",
    # "python-dotenv>=1.0.0",
    # "pydantic>=2.5.3",
]

[project.optional-dependencies]
dev = [
    # Testing
    "pytest>=7.4.4",
    "pytest-cov>=4.1.0",
    "pytest-asyncio>=0.23.3",

    # Linting & Formatting
    "black>=24.1.1",
    "ruff>=0.1.14",
    "isort>=5.13.2",

    # Type Checking
    "mypy>=1.8.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
